trigger:
  none

pr:
  none

pool:
  vmImage: 'windows-latest'
  #vmImage: 'macOS-latest'

variables:
  signingKeyStoreFilePath: 'aab-keystore.jks'
  aabFilePath: 'build/app/outputs/bundle/release/app-release.aab'
  imageFilePath: 'icon.png'

jobs:
  - job: Mobile
    displayName: Build Flutter App
    steps:
      - task: JavaToolInstaller@0
        displayName: Install Java 17
        inputs:
          versionSpec: 17
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: FlutterInstall@0
        displayName: Install Flutter
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'latest'

      - task: FlutterCommand@0
        displayName: Install flutter packages
        inputs:
          projectDirectory: '.'
          arguments: 'pub get'

      - task: FlutterCommand@0
        displayName: Change the package name
        inputs:
          projectDirectory: '.'
          arguments: 'pub run change_app_package_name:main $(APP_ID)'

      - task: PowerShell@2
        displayName: Save the icon file
        inputs:
          targetType: inline
          script: |
            [byte[]]$fileContent = [System.Convert]::FromBase64String("$(ICON_BASE64_CONTENT)")
            [IO.File]::WriteAllBytes("$(imageFilePath)", $fileContent)

      - task: FlutterCommand@0
        displayName: Generate the icons
        inputs:
          projectDirectory: '.'
          arguments: 'pub run flutter_launcher_icons'

      - task: FlutterBuild@0
        displayName: Build Flutter Android app (aab)
        inputs:
          target: 'aab'
          projectDirectory: '.'
          entryPoint: "lib/main.dart"
          iosCodesign: false
          buildName: $(APP_BUILD_NAME)
          buildNumber: $(APP_BUILD_NUMBER)

      - task: PowerShell@2
        displayName: Save signing key store file
        inputs:
          targetType: inline
          script: |
            [byte[]]$keyStoreContent = [System.Convert]::FromBase64String("$(SIGNING_STORE_BASE64_CONTENT)")
            [IO.File]::WriteAllBytes("$(signingKeyStoreFilePath)", $keyStoreContent)

      - task: PowerShell@2
        displayName: Sign Flutter Android app (aab)
        inputs:
          targetType: inline
          script: jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -storepass $(SIGNING_STORE_PASSWORD) -keystore $(signingKeyStoreFilePath) $(aabFilePath) $(SIGNING_KEY_ALIAS)

      - task: PowerShell@2
        displayName: Delete aab signing key store file
        condition: always()
        inputs:
          targetType: inline
          script: Remove-Item -Path $(signingKeyStoreFilePath) -Force 

      # - task: PowerShell@2
      #   displayName: Delete aab properties file
      #   condition: always()
      #   inputs:
      #     targetType: inline
      #     script: Remove-Item -Path "$(Build.Repository.LocalPath)/$(aabPropsFileRelativePath)" -Force 

      - task: CopyFiles@2
        displayName: Copy aab to staging directory
        condition: always()
        inputs:
          contents: '**/app-release.aab'
          targetFolder: '$(build.artifactStagingDirectory)'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          artifactName: 'drop'
      
