trigger:
  none

pr:
  none

pool:
  vmImage: 'windows-latest'
  #vmImage: 'macOS-latest'

variables:
  signingKeyStoreFilePath: 'aab-keystore.jks'
  aabPropsRelativeFilePath: 'android/aab.properties'
  aabFilePath: 'build/app/outputs/bundle/release/app-release.aab'

jobs:
  - job: Mobile
    displayName: Build Flutter App
    steps:
      - task: PowerShell@2
        displayName: Update the app id in properties file
        inputs:
          targetType: inline
          script: |
            "appId=$(APP_ID)`n" | Out-File -Filepath "$(Build.Repository.LocalPath)/$(aabPropsRelativeFilePath)" -Force

      - task: JavaToolInstaller@0
        displayName: Install Java 17
        inputs:
          versionSpec: 17
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'

      - task: FlutterInstall@0
        displayName: Install Flutter
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        displayName: Build Flutter Android app (aab)
        inputs:
          target: 'aab'
          projectDirectory: '.'
          entryPoint: "lib/main.dart"
          iosCodesign: false

      - task: PowerShell@2
        displayName: Save signing key store file
        inputs:
          targetType: inline
          script: |
            [byte[]]$keyStoreContent = [System.Convert]::FromBase64String("$(SIGNING_STORE_BASE64_CONTENT)")
            [IO.File]::WriteAllBytes("$(signingKeyStoreFilePath)", $keyStoreContent)

      - task: PowerShell@2
        displayName: Sign Flutter Android app (aab)
        inputs:
          targetType: inline
          script: jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -storepass $(SIGNING_STORE_PASSWORD) -keystore $(signingKeyStoreFilePath) $(aabFilePath) $(SIGNING_KEY_ALIAS)

      - task: PowerShell@2
        displayName: Delete aab signing key store file
        condition: always()
        inputs:
          targetType: inline
          script: Remove-Item -Path $(signingKeyStoreFilePath) -Force 

      # - task: PowerShell@2
      #   displayName: Delete aab properties file
      #   condition: always()
      #   inputs:
      #     targetType: inline
      #     script: Remove-Item -Path "$(Build.Repository.LocalPath)/$(aabPropsFileRelativePath)" -Force 

      - task: CopyFiles@2
        displayName: Copy aab to staging directory
        condition: always()
        inputs:
          contents: '**/app-release.aab'
          targetFolder: '$(build.artifactStagingDirectory)'
          OverWrite: true

      - task: PublishBuildArtifacts@1
        condition: always()
        inputs:
          artifactName: 'drop'
      
